### ISSUE TITLE
Move device definitions outside the C code

### ISSUE THREAD

**Issue by dagargo** [dagargo/overwitch#37]
To add support for new devices without the need of new releases, we need to add a JSON file with the device definitions which could be overridden by the user.

**Comment by szszoke** [comment]
Consider supporting a list of paths for the definition file.

1. Same folder as the executable file
3. Config folder in a system directory

The benefits would be that during development, you would only have to change files in the source directory.

When the application is launched, it would look for a definition file in the same folder where it was launched from and then fall back to the system-wide definition file.

**Comment by dagargo** [comment]
The idea is to implent it the same way it's in Elektroid.

This means that if the config file is found in `~/.config/overwitch/devices.json`, this will take preference over the file distributed with the package (and located with all the other resources).

See https://github.com/dagargo/elektroid#adding-and-reconfiguring-devices for more information.

This won't be in the 1.0 release but it will be in the 1.1.

**Comment by dagargo** [comment]
Implemented in 819a13c54855016f3bc5daa3c4553b3113a88b96 as mentioned above.

Besides, a `liboverwitch` shared library is installed with the binaries, which might be helpful for you. `GLib` and the JSON parsing library are not needed and can be excluded from the library by passing some options to `./configure` (see the documentation for more details), which should help with embedded-like devices. In this case, the `C` code definitions apply.

No proper API documentation yet but the utilities code should help a lot with this.

Everything is working but this is still an early stage so there are a few loose ends here and there. For instance, the header file is called `overwitch.h` but probably should be called `liboverwitch.h`.

Let me know your thoughts on all this.
