### ISSUE TITLE
ENODEV undeclared - compilation error

### ISSUE THREAD

**Issue by Lcchy** [dagargo/overwitch#42]
Hi there, thanks again for the nice project!
I have been getting a recurring error when compiling on my Rapsberry Pi as follows:
```
overwitch.c:314:11: error: ‘ENODEV’ undeclared (first use in this function)
``` 
Its fixed by adding `#include <errno.h>` to overwitch.c but I didnt want to open a PR as I imagine that there must an error in my setup to have such a straightforward and blocking error?

**Comment by dagargo** [comment]
> Hi there, thanks again for the nice project!

Always happy to hear that. :rainbow:

I've tried on my main computer (Debian), some VM (Manjaro, Ubuntu and Fedora) and my old Raspberry Pi 1 B (32 bits) running Raspbian without compilation errors.

This is my Raspbian version.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

What distribution and version are you using?

**Comment by Lcchy** [comment]
Hi, sorry for the late reply! Had a few things that came up.
I am running a RPi 4B with the [monome](https://github.com/monome/linux) linux fork, here are some details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
$ uname -a
Linux fates 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```
But if this error is only specific to this niche distrib I'm not sure this is really worth debugging. Its def not a problem to me as the fix is easy.

**Comment by dagargo** [comment]
Just to be sure, what options are you passing to `./configure`?

**Comment by Lcchy** [comment]
I only pass `CLI_ONLY=yes`

**Comment by dagargo** [comment]
I retried to compile on 3 systems with that option and couldn't replicate your issue.

Let's leave it like this.

Still, I'm leaving the issue open just in case it arises again in the near future.

Thanks for reporting this.

**Comment by Lcchy** [comment]
Yes sounds good, thanks for your help!

**Comment by dagargo** [comment]
In the end, other people were having the same issue. As it's a harmless fix, I've just added it.

Thanks for reporting this.
