### ISSUE TITLE
Digitone Keys shows up as Digitone in GUI/Jack

### ISSUE THREAD

**Issue by szszoke** [dagargo/overwitch#46]
I got a `Digitone Keys` to see if it can replace the `Digitone` and a MIDI keyboard.

The CLI is able to tell it apart from a `Digitone`:
```
$ overwitch-cli -l
0: Digitone (ID 1935:0014) at bus 001, address 020
1: Digitone Keys (ID 1935:001c) at bus 001, address 016
```

When I start `overwitch` both show up as `Digitone`. This is also true for the nodes created in Jack.
![image](https://user-images.githubusercontent.com/2766129/213517876-91f2ad1e-bf83-402c-a5b7-e6450af1f516.png)
![image](https://user-images.githubusercontent.com/2766129/213517910-41a55eab-7621-4ea1-a4c6-7418f882d25c.png)

It is also the same if I just start an `overwitch` instance for the `Digitone Keys` alone:
```
$ overwitch-cli -n 1
```

```
$ lsusb | grep Elektron
Bus 001 Device 020: ID 1935:0014 Elektron Music Machines Elektron Digitone
Bus 001 Device 016: ID 1935:001c Elektron Music Machines Elektron Digitone Keys
```

This is with only the `Digitone Keys` plugged in:
```
$ overwitch-cli -n 0 -v                      
DEBUG:overwitch.c:303:(ow_get_device_desc_from_vid_pid): Failed to open file “/home/eon/.config/overwitch/devices.json”: No such file or directory
DEBUG:overwitch.c:309:(ow_get_device_desc_from_vid_pid): Falling back to /usr/local/share/overwitch/devices.json...
DEBUG:overwitch.c:368:(ow_get_device_desc_from_vid_pid): Device with PID 28 found
DEBUG:overwitch.c:229:(ow_get_usb_device_list): Found Digitone Keys (bus 001, address 016, ID 1935:001c)
DEBUG:overwitch.c:303:(ow_get_device_desc_from_vid_pid): Failed to open file “/home/eon/.config/overwitch/devices.json”: No such file or directory
DEBUG:overwitch.c:309:(ow_get_device_desc_from_vid_pid): Falling back to /usr/local/share/overwitch/devices.json...
DEBUG:overwitch.c:368:(ow_get_device_desc_from_vid_pid): Device with PID 28 found
DEBUG:engine.c:1280:(ow_engine_load_overbridge_name): USB control in data (32 B): Digitone
DEBUG:engine.c:1300:(ow_engine_load_overbridge_name): USB control in data (16 B): 0080       1.40A
DEBUG:resampler.c:539:(ow_resampler_set_buffer_size): resampler buffer size: 1024
DEBUG:resampler.c:552:(ow_resampler_set_samplerate): resampler sample rate: 48000
```

It looks like the `Digitone Keys` is reporting itself as `Digitone`.

Would it be possible to take the device name from the JSON file that contains the device descriptors?

**Comment by dagargo** [comment]
It's even better.

Just double click on the name in the Overwitch table and rename it as you want. This changes the internal Overbridge name the devices store and it's value is kept after rebooting.

Let me know if this works because it's been a long time since I implemented this.

**Comment by szszoke** [comment]
It worked! I should have RTFM.

**Comment by dagargo** [comment]
No worries. Probably nobody tested this besides myself and needed to be done.

Glad it's working for you. 🚀
