### ISSUE TITLE
Analog Heat +FX

### ISSUE THREAD

**Issue by ianhundere** [dagargo/overwitch#49]
Anything special need to be done in order to get this to work with Analog Heat +FX?

**Comment by dagargo** [comment]
This section of the [README.md](https://github.com/dagargo/overwitch#outside-the-library) explains how to add a user-defined device.

You can copy the Analog Heat section. For what I know, the device is a 4 inputs and 4 outputs Overbridge device.

```
{
	"pid": 22,
	"name": "Analog Heat MKII",
	"input_track_names": [
		"Main L Input",
		"Main R Input",
		"FX Send L",
		"FX Send R"
	],
	"output_track_names": [
		"Main L",
		"Main R",
		"FX Return L",
		"FX Return R"
	]
}
```

The `pid` member is the base 10 value of the USB PID found with `lsusb`. Here you have the `12` value used in the Digitakt definition. Don't forget to set the device is Overbridge mode before doing this.

```
$ lsusb | grep Digitakt
Bus 001 Device 119: ID 1935:000c Elektron Music Machines Digitakt Overbridge
```

Once you have this, you can port it to the internal C library following this other [section](https://github.com/dagargo/overwitch#inside-the-library).

Pull requests are welcome.

Let me know if you manage to make this to work.

**Comment by ianhundere** [comment]
> Once you have this, you can port it to the internal C library following this other [section](https://github.com/dagargo/overwitch#inside-the-library).

ah, that's what i was missing / thanks. i'll submit a PR over the weekend, cheers. 🍻
