### ISSUE TITLE
Multiple WAVS?

### ISSUE THREAD

**Issue by briwil** [dagargo/overwitch#54]
I'm probably doing this wrong, but am I misunderstanding the purpose of this implementation of Overbridge? I installed this on my raspberry pi, I run the record command, and no matter how many tracks I have enabled, all I end up with is just one .wav file with the tracks mixed... isn't the huge benefit of overbridge that you can record each track on its own track (aka stems)?
Am I doing something wrong here?

**Comment by briwil** [comment]
I knew I was just being ignorant. Yes, I see this now, all the tracks are in there... I didn't even know such a thing was possible. Now I just need to figure out how to use this file in Logic or Ableton.

**Comment by dagargo** [comment]
You can split the multichannel output file into different mono files with this.

```
$ sox multitrack.wav track1.wav remix 1
```

Or use it in a loop like this for a faster approach. We're skipping the first 2 master stereo (tracks 1 and 2) and the input tracks (11 and 12).

```
$ for t in $(seq 3 10); do sox multitrack.wav track-$t.wav remix $t; done
```

**Comment by dagargo** [comment]
Also, [this section](https://github.com/dagargo/overwitch?tab=readme-ov-file#overwitch-record) explains you how to only record the desired tracks into the multitrack file.

This will only record the 8 individual tracks and leave the master and the inputs out.

```
$ overwitch-record -n 0 -m 001111111100
```

**Comment by briwil** [comment]
Yes, that part I knew, the multichannel file was what was beyond my understanding. Thanks so much for clarifying!
