### ISSUE TITLE
udev rules now need systemd-dev package on Debian unstable

### ISSUE THREAD

**Issue by toupeira** [dagargo/overwitch#62]
Hi there,

I just upgraded Overwitch for the first time in a while, and noticed that the udev rules weren't getting installed.

It turns out that the pkg-config file `/usr/share/pkgconfig/udev.pc` was moved from `udev` to `systemd-dev`, so after installing that package (and regenerating the `Makefile`) it worked again.

Looks like this was changed in version 253-2 of the `udev` / `systemd-dev` packages and affects both Debian testing and unstable.

**Comment by dagargo** [comment]
Thanks for reporting.

I can confirm this. Nothing was being installed on Debian testing (Trixie).

```
overwitch/udev$ sudo make install
 cd .. && /bin/bash /home/user/Desarrollo/git/overwitch/missing automake-1.16 --gnu udev/Makefile
 cd .. && /bin/bash ./config.status udev/Makefile 
config.status: creating udev/Makefile
make[1]: se entra en el directorio '/home/user/Desarrollo/git/overwitch/udev'
make[1]: No se hace nada para 'install-exec-am'.
make[1]: se sale del directorio '/home/user/Desarrollo/git/overwitch/udev'
```

As explained, the solution is to install the aforementioned package `systemd-dev`. After running the usual installation commands, running `sudo make install` from the `udev` directory installs the rules.

```
overwitch$ autoreconf
overwitch$ ./configure
[...]
overwitch/udev$ sudo make install
make[1]: se entra en el directorio '/home/user/Desarrollo/git/overwitch/udev'
make[1]: No se hace nada para 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/lib/udev/hwdb.d'
 /usr/bin/install -c -m 644 20-usb-elektron.hwdb '/usr/lib/udev/hwdb.d'
 /usr/bin/mkdir -p '/usr/lib/udev/rules.d'
 /usr/bin/install -c -m 644 20-usb-elektron.rules '/usr/lib/udev/rules.d'
make  install-data-hook
make[2]: se entra en el directorio '/home/user/Desarrollo/git/overwitch/udev'
make[2]: se sale del directorio '/home/user/Desarrollo/git/overwitch/udev'
make[1]: se sale del directorio '/home/user/Desarrollo/git/overwitch/udev'
```

Installations updated in 92a6cdac7fe3524830a88d858d00ecd129c0afed.

Can you confirm this solution addresses your issue, @toupeira?

**Comment by toupeira** [comment]
@dagargo yes that looks great, I'll go ahead and close. Thanks!
