### ISSUE TITLE
Audio stops on Xrun 

### ISSUE THREAD

**Issue by nchouba** [dagargo/overwitch#71]
Hi, 
Setup:

- Jack: 512 samples /48K
- Realtime Kernel 
- Rasperry pi 5 (bookworm through patchbox os) 
- Digitak II

whenever I get an Xrun the audio stops. is this expected? is the same happens with other Elektron devices?
ovw logs:
`
Digitakt II @ 003,002: o2h latency: 16.0 [10.7, 19.4] ms; h2o latency: -1.0 [-1.0, -1.0] ms, o2h ratio: 0.999727
Digitakt II @ 003,002: o2h latency: 15.7 [10.7, 19.4] ms; h2o latency: -1.0 [-1.0, -1.0] ms, o2h ratio: 0.999670
ERROR:jclient.c:56:jclient_thread_xrun_cb: JACK xrun
ERROR:resampler.c:448:ow_resampler_compute_ratios: Skipping DLL update (xrun)...
ERROR:resampler.c:300:ow_resampler_read_audio: Forcing o2h read (xrun)...
Digitakt II @ 003,002: o2h latency: 15.4 [10.7, 18.2] ms; h2o latency: -1.0 [-1.0, -1.0] ms, o2h ratio: 0.999879
Digitakt II @ 003,002: o2h latency: 15.5 [10.7, 18.2] ms; h2o latency: -1.0 [-1.0, -1.0] ms, o2h ratio: 0.999891
Digitakt II @ 003,002: o2h latency: 15.6 [10.7, 18.2] ms; h2o latency: -1.0 [-1.0, -1.0] ms, o2h ratio: 0.999890
`
Thanks a lot.

**Comment by dagargo** [comment]
As this was confirmed and fixed, I'm closing this as solved.

Please, reopen if the issue persists on your side.
