### ISSUE TITLE
Few bugs of overwitch-cli service mode

### ISSUE THREAD

**Issue by tothbar** [dagargo/overwitch#75]
hello all,
thanks dagaro for the systemd impumentation of overwitch-cli its pretty nice! but it has some bugs i encountered while usage.
If i run it at boot, probably it starts before the jackserver is online, and it doesnt connect to the already turned on elektron devices in my case the dtakt, and dtone.
If i start it when already both of my devices are turned on, it works perfectly.
If i run it before my devices were turned on or connected, it does connect to the first device,  then loses the connection of the first and doesnt connect to the second and gives the following message: Segmentation fault.

I believe the first case could be solved by adding to the service file the following lines 
`Requires=jack.service
After=jack.service`
or something like this.
But also to my understanding then it should be a separate systemd service file, if the user sets up overwitch to run it on boot.
Now i dont actually understand how does it run as a service..

I wanted to tri it out myself, but i couldnt find where the service file is located, if there is any. (Again its not clear to me how a cli app can run as a service in this case, and what are the rules of it)

**Comment by dagargo** [comment]
First of all I'm gonna try to document here how to create a service. After we'll go thru the bugs.

This is the systemd service configuration with @tothbar suggestions and with the modifications needed to start at boot.

```
$ cat vi /etc/systemd/user/overwitch.service 
[Unit]
Description=Overwitch service
After=pipewire.service
Requires=pipewire.service

[Service]
GuessMainPID=true
ExecStart=overwitch-cli -b 8 -s
Restart=on-failure

[Install]
WantedBy=default.target
```

To be started at boot, `WantedBy` needs to be set and `systemctl --user enable overwitch.service` needs to be run.

`After` states that the service should be started after `pipewire.service`. while `Requires` states that `pipewire.service` needs to be started. In other words, `overwitch.service` won't be started if `pipewire.service` couldn't be started.

`Restart=on-failure` is pretty obvious. If `overwitch.service` exited with error, it would be restarted.

**Comment by dagargo** [comment]
> But also to my understanding then it should be a separate systemd service file, if the user sets up overwitch to run it on boot.

With that configuration, the service just works. Or am I missing something?

>  Now i dont actually understand how does it run as a service.

I don't know exactly what you mean with that. If you mean how the code works, look at the explanation below.

---

This is a note on how the Overwitch service works.

`overwitch-cli` is just a normal process and it's not really a daemon. It's systemd the one that takes control over that process and, with all the systemd available options, it is possible to run it nicely as a proper service.

Note that not all the recommendations in the section New-Style Daemons from here are implemented. (In fact, none are on purpose but some are implicitly implemented.)

https://www.man7.org/linux//man-pages/man7/daemon.7.html

At the moment of writing this, `overwitch-cli` uses a **thread** for all the connected device either at start or when hotplugged.

It's not clear to me if there is a recommendation to spawn processes instead of using threads but I'll stick with threads for now despite that a thread ending with a `SIGSEGV` will terminate the service and force to restart everything.

**Comment by dagargo** [comment]
I have simulated having more than one device and I found a couple of bugs.

Hopefully, these have been solved in 001a5082883db53728065303cb161c1e2adca97e.

@tothbar, could you try to replicate the error and report back?

**Comment by tothbar** [comment]
Yes i will, i just didnt have my rpi available in the past few days, probably will today!

**Comment by dagargo** [comment]
I've been thinking that installing the service on `make install` might be a good idea.

**Comment by tothbar** [comment]
yes, it works for me without the segmentation error. Yes maybe it could be a flag at the ./configure step, like the CLI_ONLY

**Comment by tothbar** [comment]
thanks for your help again!

**Comment by dagargo** [comment]
I'm currrently redoing a couple of things. A new binary `overwitch-service` is being extracted from the CLI and will be used for systemd. This will eliminate the `-s` option from `overwitch-cli`.

The idea is to clearly separate all the functionality.
* `overwitch-cli`, `overwitch-play` and `overwitch-record` will only be used for single running instances and will need the device to be provided always. No config file is used and there is no D-Bus integration.
* `overwitch` and `overwitch-service` will be used for multiple running instances and will use the config file and integrate with D-Bus.

The D-Bus integration will provide mutual exclusion and only a single process of both `overwitch` and `overwitch-service` will be allowed.

**Comment by tothbar** [comment]
very cool, it will streamline things nicely!

**Comment by dagargo** [comment]
I've just pushed a few commits that implement all the aforementioned comments.

@tothbar, it would be really nice if you could take a look at the `README.md` and test this a bit.

**Comment by tothbar** [comment]
okey, it runs smoothly, my way was doing this is to start the service on startup, which isnt needed anymore! I changed the service file to Requires=jackd.service, After=jackd.service, i tought it will solve the problem, that if the overbridge device is already turned on when booting the system, it doesnt connect. But it didnt unfortunatly, at the same time its really a minor thing to look out for. I think this way the overwitch service is working pretty nicely. Why did u set the default settings to 8 bloks reather then 4? in the readme.md u say 4 is the optimal setting.

thanks, barni

**Comment by dagargo** [comment]
Thank you very much for testing this.

I forgot to mention that the systemd service is already included in the repo but it's not installed when running `make install` on the root directory. Instead, one must run `make install` from the `systemd` directory if this is their preferred way of running Overwitch. Installing it wouldn't run the service at boot so it must be enabled by the user.

> Why did u set the default settings to 8 bloks reather then 4? in the readme.md u say 4 is the optimal setting.

The lower the blocks the more overhead in the USB stack. 8 blocks (56 frames) is a very good value for me.  I typically use PipeWire with a 64 frames buffer and latency introduced by Overwitch is around 3 ms.

I'm planning on rewriting all the documentation during the following week and, if nothing else pops up, I'll release version 2.0 during the following weekend.

I'm closing this. Feel free to reopen in case of doubt.
