### ISSUE TITLE
Can't find devices on 2.0

### ISSUE THREAD

**Issue by ArAM1db33tz** [dagargo/overwitch#77]
Hi, I followed the instructions to build the new version on Arch and I can't seem to refresh and find my devices to connect them. It worked before on 1.1, is there any logs I can send to show the issue; all it shows if I launch from the terminal is:

(overwitch:13660): Gtk-WARNING **: 23:34:41.964: Unknown key gtk-modules in /home/adi/.config/gtk-4.0/settings.ini

(overwitch:13660): Gdk-WARNING **: 23:34:42.568: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)

No idea if this is bad, doesn't seem it. But I'll click the refresh button endlessly and nothing happens, I can see the elektrons fine if I switch to audio/midi usb instead. Before I downloaded from AUR and I removed the old version but not the dependencies.

**Comment by dagargo** [comment]
All Overbridge devices were upgraded with newer firmwares when Overbridge 2.13 went out. This firmware changed the way MIDI was handled and allowed MIDI to be class compliant, so the MIDI port is accessible with no drivers in Overbridge mode. As the firmware and ports were upgraded, so were the USB IDs.

Have you reinstalled the rules from the `udev` directory? This is needed to use the new USB devices (new IDs). Just run `sudo make install` from there.

If this solves your issue, the old rules files can be removed.

If this doesn't, please run `overwitch-cli -l -vvv` to list the devices in verbose mode to get more information.

**Comment by ArAM1db33tz** [comment]
Sorry I completely glazed over the updates for the boxes. works fine now apologies for my ignorance! 🥰

**Comment by dagargo** [comment]
No worries!

Glad it works for you now!

Closing this as solved.
